apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: rajendra3/myapp:1.0       # ✅ full repo + tag
        imagePullPolicy: IfNotPresent     # ✅ pull only if missing
        ports:
        - containerPort: 80

